# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout_2.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.mFile = QtWidgets.QMenu(self.menubar)
        self.mFile.setObjectName("mFile")
        self.mHelp = QtWidgets.QMenu(self.menubar)
        self.mHelp.setObjectName("mHelp")
        self.mEdit = QtWidgets.QMenu(self.menubar)
        self.mEdit.setToolTipDuration(-3)
        self.mEdit.setObjectName("mEdit")
        self.mView = QtWidgets.QMenu(self.menubar)
        self.mView.setObjectName("mView")
        self.mWindow = QtWidgets.QMenu(self.menubar)
        self.mWindow.setObjectName("mWindow")
        self.mSettings = QtWidgets.QMenu(self.menubar)
        self.mSettings.setObjectName("mSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(100, 22))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.mNew = QtWidgets.QAction(MainWindow)
        self.mNew.setShortcut("Ctrl+N")
        self.mNew.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.mNew.setObjectName("mNew")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.m_New = QtWidgets.QAction(MainWindow)
        self.m_New.setObjectName("m_New")
        self.mFile.addAction(self.m_New)
        self.menubar.addAction(self.mFile.menuAction())
        self.menubar.addAction(self.mEdit.menuAction())
        self.menubar.addAction(self.mView.menuAction())
        self.menubar.addAction(self.mSettings.menuAction())
        self.menubar.addAction(self.mWindow.menuAction())
        self.menubar.addAction(self.mHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Информационная система испытаний гидромоторов"))
        self.mFile.setTitle(_translate("MainWindow", "&Файл"))
        self.mHelp.setTitle(_translate("MainWindow", "&Помощь"))
        self.mEdit.setTitle(_translate("MainWindow", "&Правка"))
        self.mView.setTitle(_translate("MainWindow", "&Вид"))
        self.mWindow.setTitle(_translate("MainWindow", "&Окно"))
        self.mSettings.setTitle(_translate("MainWindow", "&Настройки"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.mNew.setText(_translate("MainWindow", "&Новый"))
        self.action_2.setText(_translate("MainWindow", "Просмотр"))
        self.action_3.setText(_translate("MainWindow", "Добавить гидромотор"))
        self.m_New.setText(_translate("MainWindow", "&Создать"))
        self.m_New.setShortcut(_translate("MainWindow", "Ctrl+N"))

